import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getAuthContext } from "@/lib/authz";

const inter = Inter({ subsets: ["latin"] });

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { isAdmin, name } = await getAuthContext();

  return (
    <html lang="en">
      <body className={inter.className}>
        {isAdmin ? <Navbar name={name} /> : null}
        {children}
      </body>
    </html>
  );
}
